### ISSUE TITLE
Add multiple OS check

### ISSUE THREAD

**Issue by evitalis** [cvechk/cvechk#1]
Convert OS selection dropdown to checkboxes to allow multiple OS to be reviewed at the same time.

**Comment by evitalis** [comment]
flask-wtforms has a SelectMultipleField but I do not see checkboxes as available. Will further research but may simply use the SelectMultipleField.

**Comment by evitalis** [comment]
This is pending Enterprise Linux finalizations to limit possible errors.

**Comment by StephenBrown2** [comment]
https://select2.github.io/examples.html#multiple
Alternatively for those who dislike jquery: https://angular-ui.github.io/ui-select/demo-multiple-selection.html

**Comment by evitalis** [comment]
I am going to try and implement without JS first. Once working JS can be added later. I see no reason for complex JS for such a simply thing when flask-WTF should be able to handle this. Also users may not have JS turned on and as such that would limit usage.

**Comment by evitalis** [comment]
v2 removes the UI from the actual server code so this should be handled per client. Going to close this and it will be addressed in the proper location.
