### ISSUE TITLE
Add OS option: None

### ISSUE THREAD

**Issue by evitalis** [cvechk/cvechk#15]
Allow for CVEs to be looked up without an operating system and simply retrun cve.mitre.org links only. Do not return package data for this selection.

This is to allow more flexibility for users and not for a required operating system if not needed.

**Comment by evitalis** [comment]
No need to cache this data in redis as there are no calls to the site itself. The application will simply generate a URL string and return that by itself.

**Comment by StephenBrown2** [comment]
Should the application at least verify that it is a valid CVE first?

**Comment by evitalis** [comment]
wow, I never saw this update somehow. 
If using the mitre.org site even CVEs which are not assigned have pages for them if you need/want to claim it. They just will not display info so as long as they fit the proper pattern it should be ok.

**Comment by evitalis** [comment]
Generic OS option added in v2
