### ISSUE TITLE
Account for upstream gateway errors

### ISSUE THREAD

**Issue by stephenl03** [cvechk/cvechk#21]
If the response from the Red Hat upstream API is 504, the code treats the CVE as if it is not applicable and that data is then cached for future requests, until it expires.

https://github.com/cvechk/cvechk/blob/master/cvechk/osmods/mod_rhel.py#L33

Adding a simple `while` loop with a 1 second sleep could resolve this issue.

**Comment by evitalis** [comment]
@stephenl03 I merged #22 and updated the server. Can you give this a try and let me know if the issues are resolved for you?

**Comment by stephenl03** [comment]
This is resolved.
